FROM docker.io/library/alpine:latest
WORKDIR /usr/src/app
RUN addgroup -S s3manager && adduser -S s3manager -G s3manager
RUN apk add --no-cache \
  ca-certificates \
  dumb-init
# GoReleaser puts the binary for each platform under its own directory.
ARG TARGETPLATFORM
COPY --chown=s3manager:s3manager $TARGETPLATFORM/s3manager ./
USER s3manager
EXPOSE 8080
ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "/usr/src/app/s3manager" ]
